sudo: false
language: rust
rust:
  - nightly
  - beta
  - stable
os:
  - linux
  - osx

# install Coveralls dependencies
addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev


install:
  # install travis-cargo
  - pip install 'travis-cargo<0.2' --user
  # place travis-cargo on the PATH
  - |
      if [ $TRAVIS_OS_NAME = linux ]; then
        export PATH=$HOME/.local/bin:$PATH
      fi
      if [ $TRAVIS_OS_NAME = osx ]; then
        export PATH=$HOME/Library/Python/2.7/bin:$PATH
      fi
      echo $PATH

script:
  # build
  - travis-cargo build
  # run the tests
  - travis-cargo test
  # run the benchmarks
  - travis-cargo bench

env:
  global:
  - secure: j0sm+Ru9WxUy93sluAYIhlm+TJocGYKvX4ow3MN4Dya6LSGhCXWZ/ZX0Bjd68y8FkDRAT0KMJVb846cXzqqKRgrX4x60Y3Ka6+p69Tw8DkKPjhpeBNdVWMXXgNWhuqNdlqnZxBcbQuhru84JnDq5Z/AMw1UQ4r/829kdm1aZ1ECpxnrBgXJwikGr77KWP+f/ZTNSUI53sup/1ggPndC8Kc+fPk/rItfsUi6FMFDhzyZ3VRuQLV+I2I+RRiQQUpzcn126XXXsdQM50mDFlLCkNrX/DYVIAc8l6/VIaXZ/9BVKEVs0i5zXq0Nf418tWTGx9fmKuxHLnULv7/0mP1/m2D/vEbjWVMZxDF6h3Gp+2kHTUbk8v31Fm1TTBpFC7CihOcpME9s67b9Te1wzwcvAq24A/ixcTd1u+/3nX0Vjkz9IyVIALJJoFVflnqgqlR7iMJ9h16S3NAeiqm4xCrZZRr5ab9oV2tqqWm1QF5wUM/aCcp06jQiYMnblNa9Sr6gjfcqD1hTC2zrGS5MdLAaJMJjW3qi9awJYoGLyNBxC7d8KFL6AXcyk9tRD/MZA+GeYQ27EDfboc13/Ozs08IR9OXOCaXxpfllLUTU3Vu8cCzEPqN0FO9A04jCIOAj+s/Ad+gfuZM3DEUqXaufab70CZ6AERzJNUFeusIrtfkV3m/o=
  - secure: c4Rwaqr4L5U3DFhtqwwZmpzNmLJZUhNXAkrh307T4k/98QFQMSZPyTtBSXVbHUaiVr9rAqVeVv/Q/+jKUSznLSbV5Q8eIzbbC4oHv7lpvLJTfsuFrDnhr2z51J3sZeUh4h1j2xioybdTr8zoYMVEuBLqx/x30v6swA69F8H8uroLazMPv4POHYWaIFrtzCSZZ7/r1hlasTqA2bezFcq0Hl5ZTht+GN0AsYGcQNuFV8O5KfPyeuI9HOgD43Xg1vaRlRJomtVPklifKNFmCRWhAdA8ARsgJRHbFsoddS6oJhOhtquJg6sscndVpyf0mco0POCqwij/X4rKqpH8worUm+DsYmaytvbUzTPVTo08G6ctZLo4ARoN0X09c5xux4gG79JS0M77s+iJm5f5jye66RwXD/hs5TvSX3i1odspBSLLnY5HPwXr9R2FOZ4wSPei5SyW3BpzJspIjZSFDeCVDPTA0um1gaJy35WWBwE+EeR3aKXhvSitZtKIclIw+t7T4KVgBvVbxeteo4W9rw60/Be4PyzBNUgRz7gizAxhtl4ysQnMrbaxgaijRBDxq4dkae3oBvMKOWzLydo9ZOoRY9oRP9zjkzgFfPBnDONsHi0ffFkNQKKMSwMt9EPQshlgqYZBLVP+6KGI1cDAX1c7K9oLxnZ6RRkGCgKRL2OCxeA=

after_success:
  # report coverage to coveralls (linux only)
  - |
      if [ $TRAVIS_OS_NAME = linux ]; then
        travis-cargo coveralls --no-sudo
      fi
  # report coverage to codecov.io
  - bash <(curl https://codecov.io/bash)

# triggers only if we're doing a deploy (tagged version)
# deploy triggers only on the nightly build
before_deploy:
  # build the rustdoc & upload to GitHub Pages
  - travis-cargo doc && travis-cargo doc-upload
  # build the release executable (for GitHub Releases)
  - travis-cargo build -- --release
  # package for crates.io deployment and publish
  - |
    travis-cargo package &&
    travis-cargo publish -- --token $CRATES_TOKEN

# deploy to GitHub Releases
deploy:
  provider: releases
  api_key:
    secure: NFUphxwIrSKGyM0FVjQYCLXn0nsVSXrGTeOsI59dKuEKvnG9Y2xzNIYAiRVRTdugaEgRNtx+EoI5hGNpf+7jhDRoL46IptqPUYGeurLWb482idcpEZbE3m1WIdnBIQSTzjk9CWIzZ8IVjHdP7jNDSBqL8kMq8ueKeI8ELLiDnlpN5afMv9PogN/THnUf8NorU6aqje9GPl0dwBnyOJLEF3Dyv5S+s++DzRtaIi88GwWrHb9GQBoPAUTyowsUp+nf+ka/EkS0Vhye8o1TXdI3tqEbK5kbN+vXkUStdXTOwx8h1i/1gw8TqyJ3EYEJgSwMekjCS2DdORF2KBeEjXhH3r2DjJdeEbq7+kMvHquG2SAGlb7Q0tM1M5UJQsbGUBQTMmXg/9bFUcExxfvuyWShZ6WQ+BkGy1+gNwJzP6h0l5AtDtPNz9ObEDx2JW5gJDFRypMfQJDANe9hpfOfaCTjkNt2W5cd6xJqQlEFRh7K1Y10GrtB4mGuqm0iozPcDocNQqOtCjdlHbXakunLxEYlJhSf9SqdAAg/BeUv0mdXPhzu5yUAJ84zxj3WMDP8RlKBj+CS1sTglSe7vprKVD+NC/DfBMO9UX2LgRtEv5CILZftnNWwQB5TnQ/i3eGWqbTOv+fgwZTSCZbKYyPNuJ5fT+EHaB+Y8O+I655R4ImT9nY=
  file: target/release/libseax_util.rlib
  on:
    repo: hawkw/seax_util
    rust: nightly
    tags: true
    os: linux
